Adding docs for approving Airtable entries.
service-relief/service-relief pull request #14
Opened 2020-03-22 02:09 UTC by Quinncuatro

Took me longer than I'd like to admit to find the `Approval` column in Airtable. Added some verbage to the README to let others know they need to approve entries then manually trigger a Netlify deployment to have changes show up.

2020-03-22 02:30 UTC, boborchard commented
Hey @Quinncuatro, thank you for the PR! IMHO since the change is to the starter Readme.md we probably don’t need to do a version bump. Other than that it looks good to me!

_p.s. thanks for adding the package lock to gitignore!_

2020-03-22 14:02 UTC, DSchau requested changes
Versioning is handled automatically by Lerna, so we'll want to reset those versions. Otherwise, this looks great; thank you!

2020-03-22 14:02 UTC, DSchau commented on examples/starter/package.json
> +  "version": "1.0.9",
```suggestion
  "version": "1.0.8",
```

2020-03-22 14:02 UTC, DSchau commented on examples/starter/package.json
> +    "gatsby-theme-service-relief": "^0.0.4",
```suggestion
    "gatsby-theme-service-relief": "^0.0.3",
```

2020-03-22 14:02 UTC, DSchau commented on themes/gatsby-theme-service-relief/package.json
> +  "version": "0.0.4",
```suggestion
  "version": "0.0.3",
```

2020-03-23 16:10 UTC, boborchard commented
Hey @Quinncuatro, there were a few changes requested by Dustin and it looks like there were some extra commits added as well. We'll get your work merged if you can clean it up so it only has the changes for the `Readme.md`

Thanks!

2020-03-24 13:50 UTC, Quinncuatro commented
Yeah, my bad. Tried spinning up my own version of the theme as a monorepo but haven't used monorepos before. Split off to a single repo for the theme. Let me clean this up.

2020-03-24 14:27 UTC, Quinncuatro commented
Sorry about all that. Should be a clean merge, now.

2020-03-24 14:27 UTC, Quinncuatro commented
Screw it, I don't like the messy history. Hold on.

2020-03-24 14:27 UTC, closed without merging